services:
  stable-diffusion-webui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sd-auto
    environment:
      - CLI_ARGS=--listen --api --medvram --xformers --enable-insecure-extension-access --allow-code --administrator
    restart: unless-stopped
    ports:
      - "7860:7860"
    volumes:
      - ./models:/app/models
      - ./extensions:/app/extensions
      - ./embeddings:/app/embeddings
      - ./outputs:/app/outputs
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
